server:
  port: 8761
  
  
eureka:    
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultXone: http://localhost:8761/eureka/
